on:
  push:
    branches:
      - main


jobs:
  build_css:
    name: Build SCSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: List files
        run: ls -a ./styles/css/ || mkdir -vp ./styles/css/

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.10
        with:
          source: ./styles/scss/main.scss
          destination: ./styles/css/main.css

      - name: List files
        run: ls -a ./styles/css || mkdir -vp ./styles/css

      - name: Add and Commit changes to main branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add ./styles/css/
          git commit -m 'Compiled SCSS files to CSS'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
